name: django-ci

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set environment variables
        run: |
          echo "RUTA_BACKEND=${{ secrets.RUTA_BACKEND }}" >> ./backend/.env
          echo "RUTA_FRONTEND=${{ secrets.RUTA_FRONTEND }}" >> ./backend/.env

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Migrations
        run: python backend/manage.py migrate

      - name: Run Tests
        run: python backend/manage.py test

