name: django-ci

on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Migrations
        run: |
          python backend/manage.py makemigrations
          python backend/manage.py migrate
          python backend/manage.py loaddata backend/population/01_Users.json backend/population/02_Products.json

      - name: Run Tests
        run: python backend/manage.py test
