name: react-ci
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set environment variables
        run: |
          echo "VITE_APP_BACKEND=${{ secrets.VITE_APP_BACKEND }}" >> ./frontend/.env
          echo "VITE_APP_FRONTEND=${{ secrets.VITE_APP_FRONTEND }}" >> ./frontend/.env
          echo "RUTA_BACKEND=${{ secrets.RUTA_BACKEND }}" >> ./backend/.env
          echo "RUTA_FRONTEND=${{ secrets.RUTA_FRONTEND }}" >> ./backend/.env

      - name: Install frontend dependencies
        run: |
          cd frontend/
          npm install

      - name: Start Django backend in the background
        run: |
          cd backend/
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py runserver localhost:8000 &

      - name: Run frontend build and tests
        run: |
          cd frontend/
          npm run test

      - name: Stop Django backend
        run: kill $(jobs -p) || true

